### ISSUE TITLE
Tip

### ISSUE THREAD

**Issue by LeonardLi** [Emilio66/CSDI#13]
各位在本地修改的时候请注意一下，不要每次修改都commit，注意控制下版本数，推荐使用

`git commit --amend`

可以修改上次commit的message并合并为一次commit

不然别人拉过来的时候就会发现
![d78a7f61-6c75-4e44-a0ce-98be351124af](https://cloud.githubusercontent.com/assets/5234554/16170775/b54f5d4a-3590-11e6-99ec-dbad4e5ecd6a.png)

开源项目，谢谢大家合作啦

**Comment by Emilio66** [comment]
:+1: 说的有道理，要不然大伙想看评论某次更改要费老大劲了

**Comment by LeonardLi** [comment]
话音未落又来10个commit（吃鲸）

**Comment by procr** [comment]
可以用git rebase
